#!/usr/bin/env bash
set -euo pipefail
source /data/yxx/tools/xilinx/Vitis/2024.1/settings64.sh
export TMPDIR=/home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/tmp
export TMP=/home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/tmp
export TEMP=/home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/tmp
export CPATH=/usr/include/x86_64-linux-gnu:/usr/include${CPATH:+:${CPATH}}
export C_INCLUDE_PATH=/usr/include/x86_64-linux-gnu:/usr/include${C_INCLUDE_PATH:+:${C_INCLUDE_PATH}}
export CPLUS_INCLUDE_PATH=/home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/gcc_compat${CPLUS_INCLUDE_PATH:+:${CPLUS_INCLUDE_PATH}}
export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu${LIBRARY_PATH:+:${LIBRARY_PATH}}
export COMPILER_PATH=/usr/bin${COMPILER_PATH:+:${COMPILER_PATH}}

v++ --target sw_emu --compile -D_GTHREAD_USE_COND_INIT_FUNC -DGRASU_MAX_CACHE_SEGMENT=131072 -I/home/chuxiao/GraSU/GraSU/GraSU_kernels/src -I/home/chuxiao/GraSU/GraSU/GraSU/src -I/data/yxx/tools/xilinx/Vitis_HLS/2024.1/include/etc -DSW_EMU --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/bin_search_compile.cfg -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/bin_search.sw_emu.xo /home/chuxiao/GraSU/GraSU/GraSU_kernels/src/kernel_bin_search.cpp
v++ --target sw_emu --compile -D_GTHREAD_USE_COND_INIT_FUNC -DGRASU_MAX_CACHE_SEGMENT=131072 -I/home/chuxiao/GraSU/GraSU/GraSU_kernels/src -I/home/chuxiao/GraSU/GraSU/GraSU/src -I/data/yxx/tools/xilinx/Vitis_HLS/2024.1/include/etc -DSW_EMU --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/dispatch_compile.cfg -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/dispatch.sw_emu.xo /home/chuxiao/GraSU/GraSU/GraSU_kernels/src/kernel_dispatch.cpp
v++ --target sw_emu --compile -D_GTHREAD_USE_COND_INIT_FUNC -DGRASU_MAX_CACHE_SEGMENT=131072 -I/home/chuxiao/GraSU/GraSU/GraSU_kernels/src -I/home/chuxiao/GraSU/GraSU/GraSU/src -I/data/yxx/tools/xilinx/Vitis_HLS/2024.1/include/etc -DSW_EMU -DGRASU_ENABLE_COMPLETION_TOKEN -DGRASU_PURE_PIPELINE_DIRECT_CACHE --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/process_cache_token_compile.cfg -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/process_cache.sw_emu.xo /home/chuxiao/GraSU/GraSU/GraSU_kernels/src/kernel_process_cache.cpp
v++ --target sw_emu --compile -D_GTHREAD_USE_COND_INIT_FUNC -DGRASU_MAX_CACHE_SEGMENT=131072 -I/home/chuxiao/GraSU/GraSU/GraSU_kernels/src -I/home/chuxiao/GraSU/GraSU/GraSU/src -I/data/yxx/tools/xilinx/Vitis_HLS/2024.1/include/etc -DSW_EMU -DGRASU_ENABLE_COMPLETION_TOKEN --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/process_ddr_token_compile.cfg -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/process_ddr.sw_emu.xo /home/chuxiao/GraSU/GraSU/GraSU_kernels/src/kernel_process_ddr.cpp
v++ --target sw_emu --compile -D_GTHREAD_USE_COND_INIT_FUNC -O3 -DHAVE_EDGE_PROP=1 -DHAVE_UNSIGNED_PROP=1 -DHAVE_APPLY_OUTDEG=0 -DHAVE_VERTEX_PROP=1 -DPARTITION_SIZE=65536 -DLITTLE_KERNEL_DST_BUFFER_SIZE=65536 -DBIG_KERNEL_DST_BUFFER_SIZE=524288 -DSRC_BUFFER_SIZE=4096 -DLOG2_SRC_BUFFER_SIZE=12 -DVERTEX_REORDER_ENABLE=1 -DENABLE_COMPRESSED_EDGE_INPUT=0 -DBIG_KERNEL_NUM=0 -DLITTLE_KERNEL_NUM=1 -DREGRAPH_PURE_LITTLE_ONLY -I/data/yxx/tools/xilinx/Vitis_HLS/2024.1/include/etc -I/home/chuxiao/ReGraph/acc_udfs/sssp -I/home/chuxiao/ReGraph -I/home/chuxiao/ReGraph/acc_template -I/home/chuxiao/ReGraph/acc_template/common -I/home/chuxiao/ReGraph/acc_udfs -DSW_EMU --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/kernelApply_compile.cfg -I/home/chuxiao/ReGraph/acc_template/kernel_apply -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/kernelApply.sw_emu.xilinx_u55c_gen3x16_xdma_3_202210_1.xo /home/chuxiao/ReGraph/acc_template/kernel_apply/kernel_apply.cpp
v++ --target sw_emu --compile -D_GTHREAD_USE_COND_INIT_FUNC -O3 -DHAVE_EDGE_PROP=1 -DHAVE_UNSIGNED_PROP=1 -DHAVE_APPLY_OUTDEG=0 -DHAVE_VERTEX_PROP=1 -DPARTITION_SIZE=65536 -DLITTLE_KERNEL_DST_BUFFER_SIZE=65536 -DBIG_KERNEL_DST_BUFFER_SIZE=524288 -DSRC_BUFFER_SIZE=4096 -DLOG2_SRC_BUFFER_SIZE=12 -DVERTEX_REORDER_ENABLE=1 -DENABLE_COMPRESSED_EDGE_INPUT=0 -DBIG_KERNEL_NUM=0 -DLITTLE_KERNEL_NUM=1 -DREGRAPH_PURE_LITTLE_ONLY -I/data/yxx/tools/xilinx/Vitis_HLS/2024.1/include/etc -I/home/chuxiao/ReGraph/acc_udfs/sssp -I/home/chuxiao/ReGraph -I/home/chuxiao/ReGraph/acc_template -I/home/chuxiao/ReGraph/acc_template/common -I/home/chuxiao/ReGraph/acc_udfs -DSW_EMU --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/kernelHBMWrapper_compile.cfg -I/home/chuxiao/ReGraph/acc_template/kernel_hbm_wrapper -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/kernelHBMWrapper.sw_emu.xilinx_u55c_gen3x16_xdma_3_202210_1.xo /home/chuxiao/ReGraph/acc_template/kernel_hbm_wrapper/kernel_hbm_wrapper.cpp
v++ --target sw_emu --compile -D_GTHREAD_USE_COND_INIT_FUNC -O3 -DHAVE_EDGE_PROP=1 -DHAVE_UNSIGNED_PROP=1 -DHAVE_APPLY_OUTDEG=0 -DHAVE_VERTEX_PROP=1 -DPARTITION_SIZE=65536 -DLITTLE_KERNEL_DST_BUFFER_SIZE=65536 -DBIG_KERNEL_DST_BUFFER_SIZE=524288 -DSRC_BUFFER_SIZE=4096 -DLOG2_SRC_BUFFER_SIZE=12 -DVERTEX_REORDER_ENABLE=1 -DENABLE_COMPRESSED_EDGE_INPUT=0 -DBIG_KERNEL_NUM=0 -DLITTLE_KERNEL_NUM=1 -DREGRAPH_PURE_LITTLE_ONLY -I/data/yxx/tools/xilinx/Vitis_HLS/2024.1/include/etc -I/home/chuxiao/ReGraph/acc_udfs/sssp -I/home/chuxiao/ReGraph -I/home/chuxiao/ReGraph/acc_template -I/home/chuxiao/ReGraph/acc_template/common -I/home/chuxiao/ReGraph/acc_udfs -DSW_EMU --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/kernelLittleGSMerger_compile.cfg -I/home/chuxiao/ReGraph/acc_template/kernel_little_gs_merger -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/kernelLittleGSMerger.sw_emu.xilinx_u55c_gen3x16_xdma_3_202210_1.xo /home/chuxiao/ReGraph/acc_template/kernel_little_gs_merger/kernel_little_gs_merger.cpp
v++ --target sw_emu --compile -D_GTHREAD_USE_COND_INIT_FUNC -DSW_EMU --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/pma_completion_barrier_compile.cfg -I/data/yxx/tools/xilinx/Vitis_HLS/2024.1/include/etc -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/pma_completion_barrier.sw_emu.xo /home/chuxiao/grasu-regraph-integration/kernels/pma_completion_barrier/pma_completion_barrier.cpp
v++ --target sw_emu --compile -D_GTHREAD_USE_COND_INIT_FUNC -DSW_EMU -DGRASU_REGRAPH_WEIGHTED_PMA=1 --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/pma_to_regraph_adapter_compile.cfg -I/data/yxx/tools/xilinx/Vitis_HLS/2024.1/include/etc -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/pma_to_regraph_adapter.sw_emu.xo /home/chuxiao/grasu-regraph-integration/kernels/pma_to_regraph_adapter/pma_to_regraph_adapter.cpp
v++ --target sw_emu --compile -D_GTHREAD_USE_COND_INIT_FUNC -O3 -DHAVE_EDGE_PROP=1 -DHAVE_UNSIGNED_PROP=1 -DHAVE_APPLY_OUTDEG=0 -DHAVE_VERTEX_PROP=1 -DPARTITION_SIZE=65536 -DLITTLE_KERNEL_DST_BUFFER_SIZE=65536 -DBIG_KERNEL_DST_BUFFER_SIZE=524288 -DSRC_BUFFER_SIZE=4096 -DLOG2_SRC_BUFFER_SIZE=12 -DVERTEX_REORDER_ENABLE=1 -DENABLE_COMPRESSED_EDGE_INPUT=0 -DBIG_KERNEL_NUM=0 -DLITTLE_KERNEL_NUM=1 -DREGRAPH_PURE_LITTLE_ONLY -I/data/yxx/tools/xilinx/Vitis_HLS/2024.1/include/etc -I/home/chuxiao/ReGraph/acc_udfs/sssp -I/home/chuxiao/ReGraph -I/home/chuxiao/ReGraph/acc_template -I/home/chuxiao/ReGraph/acc_template/common -I/home/chuxiao/ReGraph/acc_udfs -DSW_EMU -I/home/chuxiao/ReGraph/acc_template/kernel_little_gs --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/little_gs_stream_compile.cfg -I/home/chuxiao/grasu-regraph-integration/kernels/regraph_stream_little_gs -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/lksg_stream.sw_emu.xo /home/chuxiao/grasu-regraph-integration/kernels/regraph_stream_little_gs/little_gs_stream.cpp
