#!/usr/bin/env bash
set -euo pipefail
source /data/yxx/tools/xilinx/Vitis/2024.1/settings64.sh
export TMPDIR=/home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/tmp
export TMP=/home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/tmp
export TEMP=/home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/tmp
export CPATH=/usr/include/x86_64-linux-gnu:/usr/include${CPATH:+:${CPATH}}
export C_INCLUDE_PATH=/usr/include/x86_64-linux-gnu:/usr/include${C_INCLUDE_PATH:+:${C_INCLUDE_PATH}}
export CPLUS_INCLUDE_PATH=/home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/gcc_compat${CPLUS_INCLUDE_PATH:+:${CPLUS_INCLUDE_PATH}}
export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu${LIBRARY_PATH:+:${LIBRARY_PATH}}
export COMPILER_PATH=/usr/bin${COMPILER_PATH:+:${COMPILER_PATH}}
v++ --target sw_emu --link --kernel_frequency 200 --config /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/config/weighted_pma_native_sw_emu.cfg -D_GTHREAD_USE_COND_INIT_FUNC -I/home/chuxiao/ReGraph/acc_udfs/sssp -I/home/chuxiao/ReGraph -I/home/chuxiao/ReGraph/acc_template -I/home/chuxiao/ReGraph/acc_template/common -I/home/chuxiao/ReGraph/acc_udfs -I/home/chuxiao/ReGraph/acc_template/kernel_apply -I/home/chuxiao/ReGraph/acc_template/kernel_hbm_wrapper -I/home/chuxiao/ReGraph/acc_template/kernel_little_gs_merger -I/home/chuxiao/ReGraph/acc_template/kernel_big_gs -I/home/chuxiao/ReGraph/acc_template/kernel_big_gs_merger -o /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/grasu_regraph_weighted_pma_native.sw_emu.xclbin /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/bin_search.sw_emu.xo /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/dispatch.sw_emu.xo /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/kernelApply.sw_emu.xilinx_u55c_gen3x16_xdma_3_202210_1.xo /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/kernelHBMWrapper.sw_emu.xilinx_u55c_gen3x16_xdma_3_202210_1.xo /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/kernelLittleGSMerger.sw_emu.xilinx_u55c_gen3x16_xdma_3_202210_1.xo /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/process_cache.sw_emu.xo /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/process_ddr.sw_emu.xo /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/pma_completion_barrier.sw_emu.xo /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/pma_to_regraph_adapter.sw_emu.xo /home/chuxiao/grasu-regraph-integration/.tmp_build/weighted_pma_native_sw_emu_df7d30c/build/lksg_stream.sw_emu.xo
